### ISSUE TITLE
Compatibility with fusion/htmlparser/xmltree

### ISSUE THREAD

**Issue by thatrandomperson5** [GULPF/nimquery#18]
How would i use it with `import fusion/htmlparser/xmltree`. I need this because of script tag mismatch which caused the normal parser to break, but now i am getting errors for the below
```nim
let styles = xml.querySelectorAll("link")
```  
Any help appreciated.

**Comment by GULPF** [comment]
Fusion is essentially dead afaik (see https://github.com/nim-lang/RFCs/issues/476). The fact that fusions htmlparser has less bugs is unfortunate, ideally the bug should be fixed in the stdlib.

If you just want to get it to work you can always copy nimquery to your local project (it's only one file and no external dependencies) and try to replace the import of xmltree with the one from fusion, but it might break depending on how much fusions xmltree has deviated from the one in stdlib.
